### PR TITLE
Fix DateTime bug and many UG details

### LINKED ISSUE #126: [PE-D][Tester D] Error message of Add command does not match that of UG
App does not show that address is optional in the error message of the add command

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: erv-teo/ped#2

### LINKED ISSUE #127: [PE-D][Tester C] Error message for add command does not match user guide
In the app, the error message received for the add command indicates that the address field is compulsory (by the absence of brackets).

However that is not true as the address field is optional, as tested by me, and as stated in the user guide.

Also, the d/DATE_TIME parameter to invoke the creation of an appointment for the new patient (which is a great feature!) is also absent from the error message.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: casaarlai/ped#1

### LINKED ISSUE #132: [PE-D][Tester D] addappt does not work with "tdy"
Nothing happens when the following command is added even though it's stated in UG
addappt 1 d/tdy 10am-2pm

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: erv-teo/ped#3

### LINKED ISSUE #134: [PE-D][Tester D] add not working with "d/tdy 10am - 2pm"
nothing happens when I use the following command
add n/name p/901 d/tdy 10am - 2pm

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: erv-teo/ped#4

### LINKED ISSUE #137: [PE-D][Tester E] Wrong parameters name in UG at `addappt` section
The parameters is called DATE_TIME but the parameters in format is DATE.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: vnnamng/ped#5

### LINKED ISSUE #147: [PE-D][Tester C] Using tdy in the DATE_TIME argument for the scheduling of appointments does not work
The `tdy 10am-2pm` argument specified as one of the accepted examples of `DATE_TIME` in the user guide does not work. Trying to run the command the argument also yields no error message and instead continues to show the message from the previous command.

**Steps to reproduce:**

1. Try adding an appointment with the `addappt` command, passing in `d/tdy 10am-2pm` as an argument

**Expected behavior:**

The appointment is created for the patient with the current date and the specified time.

**Actual behavior:**

No appointment is created, and no new message is shown.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: casaarlai/ped#5

### LINKED ISSUE #162: [PE-D][Tester E] The UG does not explain what `Reset` button do
In Main GUI there is a very big and noticable `Reset` button, but UG does not explain what it do. The message return is very vauge.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: vnnamng/ped#14

### LINKED ISSUE #163: [PE-D][Tester A] Invalid example edit command given in user guide
**Steps to reproduce:**
1) Run the example command provided in the User Guide for 'Editing appointments' located on the last page of the User Guide: `editappt 1 30/12/2024 8am-9am`.

**Expected:**
The appointment located at index 1 on the Appointment List now has the date of '30/12/2024 8am-9am'.

**Actual:**
An error message is displayed showing:
'Invalid command format! 
editappt: Edits the details of the appointment identified by the index number used in the displayed appointment list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [d/DATE]...
Example: editappt 1 d/15/03/2024 9AM-2PM '

**Improvement suggestion:**
Update the example command.

**Screenshot:**

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: JonChong98/ped#4

### LINKED ISSUE #180: [PE-D][Tester A] Adding overlapping appointments is allowed
**Steps to reproduce:**
1) Add 2 patients using the `add n/NAME p/PHONE_NUMBER` command
2) Add an appointment to the first patient using `addappt <First patient index> d/02/06/2024 7am-9am`
3) Add an appointment to the second patient using `addappt <Second patient index> d/02/06/2024 7am-9am`

**Expected:**
App should not allow overlapping appointments due to conflicting time periods.

**Actual:**
App allows for adding of overlapping appointments.

**Improvement suggestion:**
The user guide does not explicitly specify whether overlapping appointments are allowed or not but from a logical standpoint, it should not be allowed. This situation is fine if each appointment had a different doctor tagged to it, but that information is not present in the app. Maybe for future iterations that could be something to expand upon?

**Screenshot:**

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: JonChong98/ped#6

### LINKED ISSUE #186: [PE-D][Tester A] Using 'tdy' as appointment DATE parameter stops add command execution
**Steps to reproduce:**
1) Run the following command: `add n/Walk in test p/12345678 d/tdy 10pm-11pm`

**Expected:**
New person created and added with the following details:
- Name: Walk in test
- Phone number: 12345678

New Appointment created and added with the following date: <Today's date> 10pm-11pm

**Actual:**
Command execution is blocked (nothing happens when you press enter to execute the command).

**Improvement suggestion:**
The command will execute if I change the parameter from 'tdy' to 'today'. Maybe there's something wrong with how the command handles the 'tdy' string parameter?

**Screenshot:**

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: JonChong98/ped#12

### LINKED ISSUE #188: [PE-D][Tester A] Parameters shown in editappt command error message do not match user guide
**Steps to reproduce:**
1) Run `editappt` to trigger a error message.

**Expected:**
Parameters shown in the error message for the `editappt` command match what is shown in user guide.

**Actual:**
Parameters shown in app are `INDEX (must be a positive integer) [d/DATE]`, which do not follow what is shown in the user guide: `INDEX d/DATE_TIME`. Parameter shown in app is missing TIME and suggests that date is optional, while user guide shows it as mandatory.

**Improvement suggestion:**
Update the parameters shown in the app error message to reflect what is shown in the user guide.

**Screenshot:**

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: JonChong98/ped#14

### LINKED ISSUE #189: [PE-D][Tester A] Using 'tdy' as appointment DATE parameter stops editappt command execution
**Steps to reproduce:**
1) Try to run the following command: `editappt 1 d/tdy 10pm-11pm`

**Expected:**
The appointment at index 1 has its date and time changed to be today's date 10pm-11pm.

**Actual:**
App does nothing and does not execute the command (pressing enter to try and execute the command does nothing). 

**Improvement suggestion:**
There may be an issue with how 'tdy' is used as a DATE parameter.

**Screenshot:**

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: JonChong98/ped#15

### LINKED ISSUE #190: [PE-D][Tester A] Incorrect appointment time is displayed when 'd/tody 10pm-11pm/10am-11am' is used as DATE_TIME input
NOTE: This bug is present in the `add` and `editappt` commands.

**Steps to reproduce:**
EDIT COMMAND:
1) Create a patient using `add n/Time Wobble p/12345678`.
2) Enter an appointment for Time Wobble patient using: `addappt <Time Wobble patient index> d/today 9am-11am`.
3) Edit the appointment using any of the following commands: 
- `editappt <Created appointment index from (2)> d/tody 10pm-11pm`
- `editappt <Created appointment index from (2)> d/tody 10am-11am`

ADD COMMAND:
1) Create a walk in patient using `add n/Time Jumble p/12345678 d/tody 10am-11am`.

**Expected:**
EDIT COMMAND:
For the first command in (3):
The appointment time is changed from '9:00am to 11:00am' to '10:00pm to 11:00pm'.

For the second command in (3):
The appointment time is changed from '9:00am to 11:00am' to '10:00AM to 11:00AM'.

ADD COMMAND:
A walk in patient is created with name 'Time Jumble', phone number '12345678' and appointment '<Today's date> 10:00AM to 11:00AM'.

**Actual:**
EDIT COMMAND
For first command in (3): 
Appointment time gets changed from '9:00am to 11:00am' to '12:00PM to 11:00PM'.

For second command in (3): 
Appointment time gets changed from '9:00am to 11:00am' to '12:00AM to 11:00AM'.

When the command is rerun again, it throws an 'This appointment already exists in the address book' error, even though the Appointment List shows it as '12:00PM to 11:00PM'/'12:00AM to 11:00AM'.

ADD COMMAND
A walk in patient is created with name 'Time Jumble', phone number '12345678' and appointment '<Today's date> 12:00AM to 11:00AM'.

**Improvement suggestion:**
Maybe it is an issue with how Appointment List itself displays the time? Since trying to run the command again triggers an '...already exists...'  error message that suggests the time is actually properly set in the data.

**Screenshot:**

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: JonChong98/ped#16

### PR DESCRIPTION
**Pull request by legionlegion**
Fixes #190, fixes #189, fixes #188, fixes #186, fixes #180, fixes #163, fixes #162, fixes #147, fixes #137, fixes #134, fixes #132, fixes #127, fixes #126

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/TimeParser.java
Comment (legionlegion) [inline src/main/java/seedu/address/logic/parser/TimeParser.java:1]: split the args to extract the hours, because length of today can vary

File: src/main/java/seedu/address/logic/parser/TimeParser.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public static AppointmentTime parse(String args) throws ParseException {
         if (matchToday.matches()) {
             LocalDate today = LocalDate.now();
             String todayString = today.format(DATE_FORMAT);
-            return new AppointmentTime(todayString + args.substring(5));
+            return new AppointmentTime(todayString + args.split(" ")[1]);
```
Comment (legionlegion) [inline src/main/java/seedu/address/logic/parser/TimeParser.java:53]: split the args to extract the hours, because length of today can vary

File: src/main/java/seedu/address/model/appointment/AppointmentTime.java [hunk 2]
```diff
@@ -23,7 +23,7 @@ public class AppointmentTime implements Comparable<AppointmentTime> {
      */
     public AppointmentTime(String time) {
         String dateString = time.substring(0, 10); // first 10 chars is the date
-        String rawTimings = time.substring(11);
+        String rawTimings = time.substring(10);
```
Comment (legionlegion) [inline src/main/java/seedu/address/model/appointment/AppointmentTime.java:26]: The hours substring actually starts from position 10 instead of 11 due to a lack of space. To visualise this, simply put a breakpoint in this function.

File: src/main/java/seedu/address/logic/parser/TimeParser.java (hunk 1 above)
Comment (minreiseah) [reply src/main/java/seedu/address/logic/parser/TimeParser.java:53]: `args.split(" ")[1]` be trimmed as well.

Comment (minreiseah) [reply src/main/java/seedu/address/logic/parser/TimeParser.java:53]: add a space after `todayString`

File: src/main/java/seedu/address/model/appointment/AppointmentTime.java (hunk 2 above)
Comment (minreiseah) [reply src/main/java/seedu/address/model/appointment/AppointmentTime.java:26]: Refer to my comments above, then you can revert this change.

**Review by minreiseah — CHANGES_REQUESTED** [review]

**Review by minreiseah — APPROVED** [review]
LGTM
