### PR TITLE
fix app not launching on certain cases of editing of json file

### LINKED ISSUE #143: [PE-D][Tester E] Change the appointment date manually wrongly in data json file cause app to not launch
The app does not launch when I change one of the date of appointment to be 32/10/2024 11am-9pm in the json file.

Result:

Expected behaviour should be an empty appointment list.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vnnamng/ped#6

### LINKED ISSUE #146: [PE-D][Tester E] Add null inside Appointment List and Person List in data json file cause the app not launching
When I insert null inside Appointment List I expect the it to ignore the null value. Instead, it does not launch.
This is similar for person List.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vnnamng/ped#7

### LINKED ISSUE #152: [PE-D][Tester E] Inconsistent date time valid check from storage
edit date time into `"10/02/2024 13am-11pm"` allow the app to still launch and auto convert into pm

but edit date time into `"10/02/2024 13am-13pm"` causes the app to not launch.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vnnamng/ped#9

### PR DESCRIPTION
**Pull request by qinboan**
resolves #152 
resolves #146 
resolves #143

### CODE REVIEW

File: src/main/java/seedu/address/MainApp.java [hunk 1]
```diff
@@ -84,9 +84,9 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
                         + " populated with a sample AddressBook.");
             }
             initialData = addressBookOptional.orElseGet(SampleDataUtil::getSampleAddressBook);
-        } catch (DataLoadingException e) {
+        } catch (Exception e) {
```
Comment (minreiseah) [inline src/main/java/seedu/address/MainApp.java:87]: Please specify the Exception being caught.

**Review by minreiseah — CHANGES_REQUESTED** [review]
