### PR TITLE
Change help window to re-open if called while open

### LINKED ISSUE #161: [PE-D][Tester E] Help window does not re-pop upon minimising
Step to reproduce:
1. type `help`
2. minimise `help` window
3. type `help` again
4. Nothing pop up (expected the help window to re-pop up)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vnnamng/ped#13

### PR DESCRIPTION
**Pull request by legionlegion**
Fixes #161 

Honestly quite a minor issue but we fixed it.

### CODE REVIEW

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -155,7 +155,8 @@ public void handleHelp() {
         if (!helpWindow.isShowing()) {
             helpWindow.show();
         } else {
-            helpWindow.focus();
+            helpWindow.close();
+            helpWindow.show();
```
Comment (minreiseah) [inline src/main/java/seedu/address/ui/MainWindow.java:159]: Nice catch on the help window not actually closing.

**Review by minreiseah — APPROVED** [review]
LGTM
